### ISSUE TITLE
Get Embedding Fails to Load UI Model

### ISSUE THREAD

**Issue by aburns4** [tobyli/Screen2Vec#2]
Hi there! I am trying to use the get_embedding.py file as instructed under the quick start portion of the readme, but I am running into an issue that seems to be caused by the saved UI model:

```
Traceback (most recent call last):
  File "get_embedding.py", line 98, in <module>
    embeddings = get_embedding(args.screen, args.ui_model, args.screen_model, args.layout_model, args.num_predictors, args.net_version)
  File "get_embedding.py", line 37, in get_embedding
    loaded_ui_model.load_state_dict(torch.load(ui_model))
  File "/scratch2/domenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HiddenLabelPredictorModel:
        Missing key(s) in state_dict: "model.embedder.text_embedder.0.auto_model.embeddings.position_ids",...
```

I am feeding in a path to my own json file that I'd like to obtain a Screen2Vec representation for, and I don't think it's related to that given where the error originates in the code.

Any idea what's going on? Thank you!

**Comment by lipopowski** [comment]
I replicated your error and I believe it's coming from additional model parameters on new pytorch versions. I've updated the code to accommodate those changes, and that fixed things on my machine, but let me know if you're still having problems!

**Comment by aburns4** [comment]
That fixed it, thanks so much!
